server:
  port: 8080
spring:
  application.name: CSV-Parser
  batch:
    chunk:
      size: 500
    input: "file:src/main/resources/input.csv"
    jdbc.initialize-schema: always
    job:
      enabled: false #setting this to false as we are running from Command Line Runner
  jpa:
    hibernate.ddl-auto: update
    hibernate.show-sql: true
    properties:
      hibernate.generate_statistics: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    initialization-mode: always
    initialize: true


logging:
  level:
    org:
      springframework:
        batch:
          repeat:
            support: ERROR


